import { LucideIcon, Braces, Lock, Clock, Code, Image, Link, Hash, FileJson, Binary, Key, Fingerprint, FileCode, Palette, FileText, RotateCw, Grid3x3, ArrowUpDown, Search, FileJson2, Eye, Edit, KeyRound, Scan, Database, FileType, FileType2, Play, Minimize2, Crop, FlipHorizontal, RotateCcw, Maximize2, Droplets, User, QrCode, ScanLine, FileImage } from 'lucide-react';

export interface Tool {
    id: string;
    name: string;
    description: string;
    icon: LucideIcon;
    iconType: string;
    category: string;
    path: string;
}

export const categories = [
    { id: 'all', name: '全部工具', icon: Braces },
    { id: 'json', name: 'JSON工具', icon: FileJson },
    { id: 'jwt', name: 'JWT工具', icon: KeyRound },
    { id: 'encode', name: '编码加密', icon: Lock },
    { id: 'time', name: '时间日期', icon: Clock },
    { id: 'format', name: '代码格式化', icon: Code },
    { id: 'text', name: '文本处理', icon: FileText },
    { id: 'image', name: '图片工具', icon: Image },
];

export const tools: Tool[] = [
    {
        id: 'json-formatter',
        name: 'JSON格式化',
        description: '在线JSON格式化、验证、压缩工具',
        icon: FileJson,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-formatter',
    },
    {
        id: 'json-compress',
        name: 'JSON压缩转义',
        description: 'JSON字符串压缩、转义和反转义',
        icon: Braces,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-compress',
    },
    {
        id: 'json-sort',
        name: 'JSON排序',
        description: '按键名对JSON对象进行排序',
        icon: ArrowUpDown,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-sort',
    },
    {
        id: 'jsonpath',
        name: 'JSONPath',
        description: 'JSON数据提取、查询',
        icon: Search,
        iconType: 'json',
        category: 'json',
        path: '/tools/jsonpath',
    },
    {
        id: 'json5',
        name: 'JSON5',
        description: 'JSON5解析验证',
        icon: FileJson2,
        iconType: 'json',
        category: 'json',
        path: '/tools/json5',
    },
    {
        id: 'json-viewer',
        name: 'JSON视图',
        description: '树形结构展示JSON',
        icon: Eye,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-viewer',
    },
    {
        id: 'json-editor',
        name: 'JSON编辑器',
        description: '可视化编辑JSON',
        icon: Edit,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-editor',
    },
    {
        id: 'jwt',
        name: 'JWT加解密',
        description: 'JWT Token编码解码',
        icon: KeyRound,
        iconType: 'jwt',
        category: 'jwt',
        path: '/tools/jwt',
    },
    {
        id: 'jwt-decode',
        name: 'JWT解密 高精度版',
        description: '精确解析JWT各部分',
        icon: Scan,
        iconType: 'jwt',
        category: 'jwt',
        path: '/tools/jwt-decode',
    },
    {
        id: 'json-to-sql',
        name: 'JSON转SQL',
        description: '将JSON数据转换为SQL语句',
        icon: Database,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-to-sql',
    },
    {
        id: 'sql-to-json',
        name: 'SQL转JSON',
        description: 'SQL转JSON结构',
        icon: FileJson,
        iconType: 'json',
        category: 'json',
        path: '/tools/sql-to-json',
    },
    {
        id: 'sql-to-java',
        name: 'SQL转Java',
        description: 'SQL表结构转Java实体类',
        icon: FileCode,
        iconType: 'json',
        category: 'json',
        path: '/tools/sql-to-java',
    },
    {
        id: 'json-to-java',
        name: 'JSON转Java实体',
        description: 'JSON转Java POJO类',
        icon: FileType,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-to-java',
    },
    {
        id: 'json-to-python',
        name: 'JSON转Python类',
        description: 'JSON转Python dataclass',
        icon: FileType2,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-to-python',
    },
    {
        id: 'json-to-schema',
        name: 'JSON转JSON Schema',
        description: '从JSON生成JSON Schema',
        icon: FileJson2,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-to-schema',
    },
    {
        id: 'json-to-objc',
        name: 'JSON转ObjectiveC',
        description: 'JSON转OC模型类',
        icon: FileCode,
        iconType: 'json',
        category: 'json',
        path: '/tools/json-to-objc',
    },
    {
        id: 'lottie-preview',
        name: 'Lottie动画预览',
        description: '预览Lottie JSON动画',
        icon: Play,
        iconType: 'image',
        category: 'image',
        path: '/tools/lottie-preview',
    },
    {
        id: 'base64',
        name: 'Base64编解码',
        description: '文本与Base64互转，支持图片',
        icon: Binary,
        iconType: 'encode',
        category: 'encode',
        path: '/tools/base64',
    },
    {
        id: 'url-encode',
        name: 'URL编解码',
        description: 'URL编码与解码转换工具',
        icon: Link,
        iconType: 'encode',
        category: 'encode',
        path: '/tools/url-encode',
    },
    {
        id: 'md5',
        name: 'MD5加密',
        description: 'MD5哈希值计算工具',
        icon: Fingerprint,
        iconType: 'encode',
        category: 'encode',
        path: '/tools/md5',
    },
    {
        id: 'uuid',
        name: 'UUID生成器',
        description: '在线生成UUID/GUID',
        icon: Key,
        iconType: 'encode',
        category: 'encode',
        path: '/tools/uuid',
    },
    {
        id: 'timestamp',
        name: 'Unix时间戳',
        description: '时间戳与日期时间互转',
        icon: Clock,
        iconType: 'time',
        category: 'time',
        path: '/tools/timestamp',
    },
    {
        id: 'code-formatter',
        name: '代码格式化',
        description: 'JS/CSS/HTML/SQL代码格式化',
        icon: FileCode,
        iconType: 'format',
        category: 'format',
        path: '/tools/code-formatter',
    },
    {
        id: 'color-converter',
        name: '颜色转换',
        description: 'HEX/RGB/HSL颜色格式互转',
        icon: Palette,
        iconType: 'image',
        category: 'image',
        path: '/tools/color-converter',
    },
    {
        id: 'hash',
        name: '哈希计算',
        description: 'SHA1/SHA256/SHA512哈希计算',
        icon: Hash,
        iconType: 'encode',
        category: 'encode',
        path: '/tools/hash',
    },
    {
        id: 'text-diff',
        name: '文本对比',
        description: '在线文本内容对比工具',
        icon: FileText,
        iconType: 'text',
        category: 'text',
        path: '/tools/text-diff',
    },
    {
        id: 'case-converter',
        name: '大小写转换',
        description: '驼峰/下划线/大小写转换',
        icon: RotateCw,
        iconType: 'text',
        category: 'text',
        path: '/tools/case-converter',
    },
    {
        id: 'image-grid',
        name: '九宫格切图',
        description: '将图片分割为9宫格，支持单独或批量下载',
        icon: Grid3x3,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-grid',
    },
    {
        id: 'image-compress',
        name: '图片压缩',
        description: '压缩图片文件大小，支持质量调节',
        icon: Minimize2,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-compress',
    },
    {
        id: 'image-crop',
        name: '图片裁剪',
        description: '自定义裁剪图片区域',
        icon: Crop,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-crop',
    },
    {
        id: 'image-flip',
        name: '图片翻转',
        description: '水平或垂直翻转图片',
        icon: FlipHorizontal,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-flip',
    },
    {
        id: 'image-rotate',
        name: '图片旋转',
        description: '旋转图片角度',
        icon: RotateCcw,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-rotate',
    },
    {
        id: 'image-resize',
        name: '缩放照片',
        description: '调整图片尺寸大小',
        icon: Maximize2,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-resize',
    },
    {
        id: 'image-watermark',
        name: '图片加水印',
        description: '给图片添加文字水印',
        icon: Droplets,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-watermark',
    },
    {
        id: 'id-photo-bg',
        name: '证件照背景',
        description: '更换证件照背景颜色',
        icon: User,
        iconType: 'image',
        category: 'image',
        path: '/tools/id-photo-bg',
    },
    {
        id: 'qrcode-generate',
        name: '二维码生成',
        description: '生成自定义二维码',
        icon: QrCode,
        iconType: 'image',
        category: 'image',
        path: '/tools/qrcode-generate',
    },
    {
        id: 'qrcode-scan',
        name: '二维码解析识别',
        description: '识别并解析二维码内容',
        icon: ScanLine,
        iconType: 'image',
        category: 'image',
        path: '/tools/qrcode-scan',
    },
    {
        id: 'image-to-svg',
        name: '图片转SVG',
        description: '将位图转换为SVG矢量图',
        icon: FileImage,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-to-svg',
    },
    {
        id: 'pdf-to-image',
        name: 'PDF转图片',
        description: '将PDF文件转换为图片',
        icon: FileImage,
        iconType: 'image',
        category: 'image',
        path: '/tools/pdf-to-image',
    },
    {
        id: 'image-to-pdf',
        name: '图片转PDF',
        description: '将图片转换为PDF文件',
        icon: FileImage,
        iconType: 'image',
        category: 'image',
        path: '/tools/image-to-pdf',
    },
    {
        id: 'gemini-watermark',
        name: '去Gemini水印',
        description: '去除Gemini AI生成图片的水印',
        icon: Droplets,
        iconType: 'image',
        category: 'image',
        path: '/tools/gemini-watermark',
    },
];
